[project]
name = "web_scraping"
version = "0.1.0"
description = "Add a short description here"
authors = ["coltonrobbins73 <coltonrobbins73@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
requests = ">=2.31.0,<2.32"
beautifulsoup4 = ">=4.12.3,<4.13"

